package com.dillian.initiateservice.util

const val FUNDS_STARTING_AMOUNT = 5000
const val POPULARITY_STARTING_AMOUNT = 4000
const val RESEARCH_STARTING_AMOUNT = 10
const val SOLAR_PANEL_BASIC_PRODUCTION = 10
const val SOLAR_PANEL_BASIC_RESEARCH = 1
const val SOLAR_PANEL_BASIC_GOLD_INCOME = 1
const val SOLAR_PANEL_BASIC_ENVIRONMENTAL_SCORE = 1
const val STARTING_TILE_AMOUNT = 80